### ISSUE TITLE
React-DOM may emit server-client mismatch warnings

### ISSUE THREAD

**Issue by ivan-aksamentov** [ivan-aksamentov/reactlandia-bolerplate-lite#2]
On client side (in browser console) React-DOM may emit a server-client mismatch warning:
 
    Warning: Text content did not match. Server: "Home" Client: "Loading..."

(instead of `Home` there may be any other "page" component)
  
This is likely due to the server emitting the fully rendered final component, while client *renders* "Loading" placeholder component on top of it.

It feels like something really bad is happening behind the scenes and this    warning should be carefully investigated. In fact, why client even tries to     render anything? Shouldn't it only hydrate the server-side-rendered `Home` component?

**Comment by Enalmada** [comment]
I could not reproduce this yet...granted I have not used it very much yet.  I would be curious if there was any other steps you can think of to reproduce this.

**Comment by ivan-aksamentov** [comment]
I forgot to mention that for repro you need to upgrade `react-universal-component` to `3.0.0`. With `2.9.0`, as we use now, indeed, warning do not occur. I guess this problem is caused by #3.

**Comment by ivan-aksamentov** [comment]
@Enalmada I have just discovered a really bad workaround. Described in [#3](https://github.com/ivan-aksamentov/reactlandia-bolerplate-lite/issues/3#issuecomment-413647769)

**Comment by ivan-aksamentov** [comment]
This is resolved now, when we upgraded to `"react-universal-component": "^4.0.0-alpha.0"`
