### ISSUE TITLE
webpack-flush-chunks thinks it is unable to find the page chunks

### ISSUE THREAD

**Issue by ivan-aksamentov** [ivan-aksamentov/reactlandia-bolerplate-lite#3]
After upgrading `react-universal-component` to version `3.0.0`, `webpack-flush-chunks` emits the following warning  for every universal component (`../pages/Home` in this example):

    [FLUSH CHUNKS]: Unable to find pages-Home in Webpack chunks. 
    Please check usage of Babel plugin.

See [webpack-flush-chunks/src/flushChunks.js:213](https://github.com/faceyspacey/webpack-flush-chunks/blob/f66b2f15bcac0d43e24a98be156fff6c51a15609/src/flushChunks.js#L213-L216)
  
I heard it can be due to double-bundling or improper setup of Webpack externals. The second seems unlikely, as we don't use externals in this project. 

Message does not appear with `react-universal-component 2.9.0` (so we rolled back to this version)

**Comment by ScriptedAlchemy** [comment]
Do you have any externals listed, like the universal ones?

**Comment by ivan-aksamentov** [comment]
@ScriptedAlchemy 
No, we don't use [`webpack.externals`](https://webpack.js.org/configuration/externals/) at all. Should we?

Here is webpack config: 
[`webpack/client.js`](https://github.com/ivan-aksamentov/reactlandia-bolerplate-lite/blob/v0.1.6/webpack/client.js) (as of version v0.1.6)

**Comment by ivan-aksamentov** [comment]
In fact, I just discovered that if I move `src/components/Switcher.js` (containing `Switcher` and `UniversalPage` components and the dynamic import itself) to `src/pages/Switcher.js` (where all "page" components are), and update import paths accordingly, the issue goes away, along with issue #2. I think that the difference in component path plays some role here.

The issues observed when dynamic imports are like this:

    const UniversalPage = universal(({ page }) => import(`../pages/${page}`), {

And when `Switcher` and `UniversalPage` are moved into the same dir, it becomes:

    const UniversalPage = universal(({ page }) => import(`./${page}`), {

Coupled with #6, I think the target for the investigation is how `react-universal-component` deals with paths. I am looking into it, but so far it seems to be very tricky.

**Comment by Enalmada** [comment]
Small silver lining but I think you are lucky that you can isolate the problem to changes that happened between 2.9 and 3.  The only feature I see explicitly called out in the release is "Convert chunk names to dashes instead of slashes".   It could be interesting to manually roll back some of the major changes that went into the release and see if it fixes the issue but that may not be practical...just thinking aloud.

**Comment by ScriptedAlchemy** [comment]
When it says server missmatch, it usually means the universal importer is inside the folder its supposed to import

**Comment by ScriptedAlchemy** [comment]
if you move the `const UniversalPage = universal(({ page }) => import(`./${page}`), {`

up one directory, and point it to the directory. it works. This is a new but and have been unable to solve it yet

**Comment by nvdlug** [comment]
Hey @ScriptedAlchemy 

I did that but i still get ``[FLUSH CHUNKS]: Unable to find pages-Home in Webpack chunks. Please check usage of Babel plugin`` error the first time I load home. Am I missing something.

**Comment by ivan-aksamentov** [comment]
This is resolved now, when we upgraded to `"react-universal-component": "^4.0.0-alpha.0"`

**Comment by ScriptedAlchemy** [comment]
❤️❤️
